### ISSUE TITLE
A problem in "runApp"

### ISSUE THREAD

**Issue by miharbi1982** [AntoineSoetewey/statistics-201#1]
Hi Antoine,
Thanks for this great work.
When I run the code, I encountered the following error message:
`Warning in checkEncoding(file) :
  The input file C:\Users\lenovo\Documents\miharbi/app.R does not seem to be encoded in UTF8
Warning in readLines(file, warn = FALSE) :
  invalid input found on input connection 'C:\Users\lenovo\Documents\miharbi/app.R'
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  C:\Users\lenovo\Documents\miharbi/app.R:243:18: unexpected INCOMPLETE_STRING
244:         src="http://i.creativecommons.org/l/by/2.0/be/80x15.png"/></a> Cette oeuvre de <span xmlns:cc="http://creativecommons.org/ns#"
245:         property="cc:attributionName"><font face="Courier">RShiny@UCLouvain</font></span> est mise 
Error in sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)) : 
  Error sourcing C:\Users\lenovo\AppData\Local\Temp\RtmpaSXhe6\fileb341489ba`
What's the solution please?

**Comment by AntoineSoetewey** [comment]
Dear Brahim,

Try again by removing lines [243 to 248](https://github.com/AntoineSoetewey/statistics-201/blob/master/app.R#L243-L248) or by changing the encoding to UTF-8.

I close the issue, you can reopen it if it still doesn't work.

Best,
Antoine

**Comment by AntoineSoetewey** [comment]
I just translated lines [243 to 248](https://github.com/AntoineSoetewey/statistics-201/blob/master/app.R#L243-L248) from French to English with this [commit](https://github.com/AntoineSoetewey/statistics-201/commit/7cc9093c5c4ec1d2ec45153f883d24f64ef8865e). So you don't even have to remove those lines anymore. You can simply try again with the new version of the app.

**Comment by miharbi1982** [comment]
It's working!
Another question, please
The sample should be charged manually? Is there no way to download from a file CSV, for example?
Many thank Antoine.

**Comment by AntoineSoetewey** [comment]
At the moment the sample should be charged manually.

Downloading from a CSV file would require quite a bit of time to edit the code of the app. I don't have the time to do it at the moment unfortunately. I keep your suggestion if I find some time in the future, or if you are familiar with R and Shiny app, feel free to propose a pull request with these changes!

Best,
Antoine

**Comment by miharbi1982** [comment]
I wish you all the best!
