### ISSUE TITLE
failed to runAPP due to warings in checkEncoding(file)

### ISSUE THREAD

**Issue by q674818689** [AntoineSoetewey/statistics-201#3]
I was trying to runApp(Shiny),and the console shows errors as follows, and still confusing how to solve this problem

> shiny::runApp()
Loading required package: shiny
Warning in checkEncoding(file) :
  The input file F:\app/app.R does not seem to be encoded in UTF8
Warning in readLines(file, warn = FALSE) :
  输入链结'F:\app/app.R'内的输入不对
Loading required package: gsubfn
Loading required package: proto
Loading required package: RSQLite
Loading required package: sysfonts
Loading required package: showtextdb
Error in func(fname, ...) : app.R did not return a shiny.appobj object.
>

**Comment by AntoineSoetewey** [comment]
Can you check if this [issue](https://github.com/AntoineSoetewey/statistics-201/issues/1) fix your problem?

**Comment by q674818689** [comment]
thank you Antoine, it really helps a lot. choose encoding UTF8 when reopen file with UTF-8 ,and finally problems solved.

**Comment by AntoineSoetewey** [comment]
Glad you managed to fix it!
