### ISSUE TITLE
Missing sqrt in calculation

### ISSUE THREAD

**Issue by joshua-morten** [AntoineSoetewey/statistics-201#4]
https://github.com/AntoineSoetewey/statistics-201/blob/7c41bd2b8385cced5ca6373905f78d5f695e827d/app.R#L1074

There is a sqrt missing in the calculation of the test statistic throughout all the prop.z.test* calculations.

**Comment by joshua-morten** [comment]
Realized you were passing it already square rooted.

**Comment by AntoineSoetewey** [comment]
No problem. Don't hesitate to let me know if you find another typo (it's not impossible with so much computations).

Regards,
Antoine
